# Generated by Django 4.1.1 on 2024-01-19 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('bus_number', models.CharField(max_length=30)),
                ('status', models.IntegerField(choices=[(1, 'Planned'), (2, 'In Progress'), (3, 'Completed'), (4, 'Cancelled'), (5, 'Delayed'), (6, 'On Hold'), (7, 'Expired')])),
                ('price', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('from_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_from', to='trip.area')),
                ('to_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_to', to='trip.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
