# Generated by Django 4.1.1 on 2022-09-17 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='الإسم')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإضافة')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='وقت التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
            ],
            options={
                'verbose_name': 'المؤسسه التعليمية',
                'verbose_name_plural': 'المؤسسات التعليمية',
                'db_table': 'institution',
                'managed': True,
            },
        ),
    ]
